# **TOÁN ỨNG DỤNG VÀ THỐNG KÊ**

# **Đồ án Gauss**

## **Mục lục**

* [Thông tin sinh viên](#c1)
* [Bài toán và giải thuật](#c2)
* [Lập trình không sử dụng thư viện](#c3)
* [Sử dụng thư viện `numpy`](#c4)
* [Sử dụng thư viện `sympy`](#c5)
* [So sánh kết quả và nhận xét chung](#c6)
* [Mô tả ý tưởng thực hiện và các hàm](#c7)

# =============================================================================
# **PHẦN THÔNG TIN SINH VIÊN** <a id="c1"></a>
# =============================================================================

## **Họ và tên:** Nguyễn Hải Đăng

## **Mã số sinh viên:** 23127165

## **Lớp:** 23CLC03

# =============================================================================
# **PHẦN BÀI TOÁN VÀ GIẢI THUẬT** <a id="c2"></a>
# =============================================================================

## **Mô tả bài toán**

Bài toán yêu cầu xây dựng hai hàm chính để giải hệ phương trình tuyến tính `Ax = b`:
1.  `Gauss_elimination(A_augmented)`: Nhận đầu vào là ma trận mở rộng `[A|b]` và trả về ma trận dạng bậc thang.
2.  `back_substitution(A_echelon)`: Nhận đầu vào là ma trận dạng bậc thang và trả về nghiệm của hệ (duy nhất, vô số nghiệm, hoặc thông báo vô nghiệm).

## **Giải hệ phương trình tuyến tính**

Hệ phương trình tuyến tính $A\boldsymbol{x} = \boldsymbol{b}$ thường được giải bằng các bước:

**Bước 1.** Lập **ma trận bổ sung** (augmented matrix) bằng cách ghép cột $\boldsymbol{b}$ sau ma trận $A$: $\bar{A} = \left[ A | \boldsymbol{b} \right]$.

**Bước 2.** Dùng các phép biến đổi sơ cấp trên dòng để biến đổi $\bar{A}$ thành ma trận tương đương dòng có dạng bậc thang $R$.

**Bước 3.** Giải $R$ bằng **phép thế ngược** (back-substitution) để có nghiệm.


## **Khử Gauss (Gaussian Elimination)**

Khử Gauss là phương pháp biến đổi tương đương dòng, giúp đưa ma trận về dạng **bậc thang**. Các bước thực hiện như sau:

**Bước 1: Xác định cột trái nhất không chứa toàn số 0**
Tìm cột đầu tiên từ trái sang phải, trong đó có ít nhất một phần tử khác 0.


**Bước 2: Đổi chỗ hai dòng (nếu cần thiết)**
Nếu phần tử đầu tiên khác 0 không nằm ở dòng đầu tiên, đổi chỗ dòng đó với một dòng khác chứa số hạng khác 0.

> - **Lựa chọn đơn giản**: Chọn dòng đầu tiên có số hạng khác 0. (đây là cách chọn cho code phía dưới)
> - **Chiến lược partial pivoting**: Chọn dòng có số hạng với trị tuyệt đối lớn nhất để tăng độ chính xác. 

**Bước 3: Biến số dẫn đầu thành 1 (Tùy chọn)**
Với số hạng đầu cột (\( a \neq 0 \)) nhận được từ Bước 2, nhân toàn bộ dòng chứa \( a \) với \( \frac{1}{a} \) để biến nó thành số dẫn đầu 1 (*leading 1*).

**Bước 4: Biến các số hạng bên dưới số dẫn đầu thành 0**
Dùng số dẫn đầu ở dòng hiện tại để loại bỏ tất cả số hạng bên dưới trong cùng cột bằng cách cộng thêm các bội số thích hợp của dòng đó.

**Bước 5: Tiếp tục với phần còn lại**
Che dòng đã làm xong và lặp lại các bước trên với phần ma trận chưa xử lý, cho đến khi toàn bộ ma trận đạt dạng bậc thang.

**Ghi chú**
- Nếu tại bất kỳ bước nào, toàn bộ số hạng trong một dòng không chứa phần tử khác 0 nhưng cột tự do lại khác 0, hệ phương trình **vô nghiệm**.
- Nếu sau khi thực hiện đầy đủ, vẫn còn biến tự do, hệ phương trình có **vô số nghiệm**.
- Nếu không có biến tự do, hệ phương trình có **nghiệm duy nhất**.


## **Giải thuật Back Substitution**

**Bước 1.** Xác định các biến chính và biến tự do:
- **Với mỗi dòng \(i\)** trong ma trận:
  - Xác định cột không bằng 0 đầu tiên \(j\).
  - Nếu \(j = n\) (cột hệ số tự do), kết luận rằng hệ **vô nghiệm**.
  - Nếu không, thêm \(j\) vào danh sách các **biến chính**.
- Các cột không nằm trong danh sách biến chính được gọi là **biến tự do**.

**Bước 2.** Xử lý nghiệm:
- **Nếu không có biến tự do:**
  - Bắt đầu từ dòng cuối, tính toán mỗi biến chính bằng cách thay thế các giá trị đã tính trước đó.
  - Lưu kết quả vào một danh sách và trả về như **nghiệm duy nhất**.

- **Nếu có biến tự do:**
  - Gán tham số $t_1, t_2, \ldots$ cho từng biến tự do.
  - Tính các biến chính dưới dạng biểu thức tuyến tính của các tham số.
  - Trả về nghiệm dưới dạng một tập hợp phương trình biểu diễn **nghiệm tổng quát**.

# =============================================================================
# **PHẦN LẬP TRÌNH** <a id="c3"></a>
# =============================================================================

In [26]:
# Đây là các bài toán và ta sẽ lưu nó dưới dạng 1 ma trận các bài toán

prob1 = [
    [1,2,-1,-1],
    [2,2,1,1],
    [3,5,-2,-1],
]

prob2 = [
    [1,-2,-1,1],
    [2,-3,1,6],
    [3,-5,0,7],
    [1,0,5,9]
]

prob3 = [
    [1,2,0,2,6],
    [3,5,-1,6,17],
    [2,4,1,2,12],
    [2,0,-7,11,7]
]

prob4 = [
    [2,-4,-1,1],
    [1,-3,1,1],
    [3,-5,-3,2]
]

prob5 = [
    [1,2,-2,3],
    [3,-1,1,1],
    [-1,5,-5,5]
]

prob6 = [
    [2,-4,6,8],
    [1,-1,1,-1],
    [1,-3,4,0]
]
prob7 = [
    [4,-2,-4,2,1],
    [6,-3,0,-5,3],
    [8,-4,28,-44,11],
    [-8,4,-4,12,-5]
]

prob8 = [
    [1,-2,3,-3],
    [2,2,0,0],
    [0,-3,4,1],
    [1,0,1,-1]
]

prob9 = [
    [3,-3,3,-3],
    [-1,-5,2,4],
    [0,-4,2,2],
    [3,-1,2,-4]
]

prob10 = [
    [1,-1,1,-3,0],
    [2,-1,4,-2,0]
]

prob11 = [
    [2,-3,4,-1,0],
    [6,1,-8,9,0],
    [2,6,1,-1,0]
]

prob12 = [
    [1,6,4,0],
    [2,4,-1,0],
    [-1,2,5,0]
]

problems = [prob1, prob2, prob3, prob4, prob5, prob6, prob7, prob8, prob9, prob10, prob11, prob12]

In [27]:
def deepcopy_matrix(matrix):
    return [row[:] for row in matrix]

In [28]:
def Gauss_elimination(A_orig):
    A = deepcopy_matrix(A_orig)  
    rows = len(A)
    cols = len(A[0])

    i = 0  
    j = 0  

    while i < rows and j < cols - 1:  
        # 1. Tìm cột pivot_cols
        pivot_col = -1  
        for c in range(j, cols - 1): 
            has_nonzero = False
            for r in range(i, rows): 
                if A[r][c] != 0:
                    has_nonzero = True
                    break
            if has_nonzero:
                pivot_col = c
                break
        if pivot_col == -1:
            break

        # 2. Tìm hàng pivot_row
        pivot_row = -1
        for k in range(i, rows):
            if A[k][pivot_col] != 0:
                pivot_row = k
                break  

        if pivot_row != i:
            A[i], A[pivot_row] = A[pivot_row], A[i]  

        # 3.Chuẩn hoá
        pivot_element = A[i][pivot_col]
        if pivot_element != 0:  
            for c in range(pivot_col, cols):  
                A[i][c] /= pivot_element

            # 4. Khử
            for k in range(i + 1, rows):
                multiplier = A[k][pivot_col]
                for c in range(pivot_col, cols):
                    A[k][c] -= multiplier * A[i][c]
        else:
            print("WARNING: Pivot element is zero. This could indicate a singular matrix or numerical instability.") 

        i += 1  
        j = pivot_col + 1

    return A

In [29]:
def back_substitution(A: list) -> list | None:
    num_rows = len(A)
    num_cols = len(A[0])
    num_variables = num_cols - 1 

    # Hằng số epsilon để so sánh số thực
    EPSILON = 1e-9 

    if num_variables <= 0:
        print("Lỗi: Không có biến nào để giải hoặc ma trận không hợp lệ.")
        for r_idx in range(num_rows):
            if abs(A[r_idx][0]) > EPSILON:
                print("Hệ vô nghiệm (0 = c != 0).")
                return None
        print("Hệ có nghiệm tùy ý (0 = 0) hoặc không có biến.")
        return [] 

    # --- Bước 1: Xác định vị trí các phần tử đầu mỗi hàng (pivot) ---
    pivot_col_for_row = [-1] * num_rows
    for r_idx in range(num_rows):
        for c_idx in range(num_variables): 
            if abs(A[r_idx][c_idx]) > EPSILON:
                pivot_col_for_row[r_idx] = c_idx
                break
        if pivot_col_for_row[r_idx] == -1 and abs(A[r_idx][num_cols - 1]) > EPSILON:
            print("Hệ vô nghiệm (dòng [0...0 | k] với k != 0).")
            return None

    # --- Bước 2: Xác định biến cơ sở và biến tự do ---
    pivot_variable_indices = set() 
    for c_idx in pivot_col_for_row:
        if c_idx != -1:
            pivot_variable_indices.add(c_idx)

    free_variable_indices = []
    for var_idx in range(num_variables):
        if var_idx not in pivot_variable_indices:
            free_variable_indices.append(var_idx)

    # --- Bước 3: Giải hệ ---
    solution_expressions = [0.0] * num_variables 

    if not free_variable_indices:
        # --- Trường hợp 3a: Nghiệm duy nhất ---
        print("Hệ có nghiệm duy nhất.")
        solution_values = [None] * num_variables 

        for r_idx in range(num_rows - 1, -1, -1):
            current_pivot_col = pivot_col_for_row[r_idx]

            if current_pivot_col == -1: 
                continue

            rhs_value = A[r_idx][num_cols - 1]
            sum_known_terms = 0.0
            for c_idx_sum in range(current_pivot_col + 1, num_variables):
                if solution_values[c_idx_sum] is not None:
                     sum_known_terms += A[r_idx][c_idx_sum] * solution_values[c_idx_sum]
            
            pivot_element = A[r_idx][current_pivot_col]
            if abs(pivot_element) < EPSILON:
                if abs(rhs_value - sum_known_terms) > EPSILON : 
                    print(f"Hệ trở thành vô nghiệm do mâu thuẫn tại hàng {r_idx} (pivot gần bằng 0).")
                    return None
                else: 
                    print(f"Mâu thuẫn: Pivot gần bằng 0 tại hàng {r_idx} nhưng hệ được cho là có nghiệm duy nhất.")
                    return None 
            
            solution_values[current_pivot_col] = (rhs_value - sum_known_terms) / pivot_element
            solution_expressions[current_pivot_col] = solution_values[current_pivot_col]

        for i in range(num_variables):
            val = solution_expressions[i]
            if isinstance(val, float):
                 print(f'x{i + 1} = {val:.5f}')
            else:
                 print(f'x{i + 1} = {val}')
        return solution_expressions

    else:
        # --- Trường hợp 3b: Vô số nghiệm ---
        print("Hệ có vô số nghiệm.")
        
        for var_idx in range(num_variables):
            if var_idx in free_variable_indices:
                solution_expressions[var_idx] = {'is_free': True, var_idx: 1.0} 
            else: 
                expr_dict = {'is_free': False, 'constant_term': 0.0}
                for f_idx in free_variable_indices:
                    expr_dict[f_idx] = 0.0 
                solution_expressions[var_idx] = expr_dict

        for r_idx in range(num_rows - 1, -1, -1):
            current_pivot_col = pivot_col_for_row[r_idx]

            if current_pivot_col == -1: 
                continue

            if not isinstance(solution_expressions[current_pivot_col], dict) or \
               solution_expressions[current_pivot_col].get('is_free'):
                 print(f"Lỗi logic: Biến cơ sở x{current_pivot_col+1} không được khởi tạo đúng cách cho vô số nghiệm.")
                 return None

            pivot_var_expr = solution_expressions[current_pivot_col] 
            
            pivot_var_expr['constant_term'] = A[r_idx][num_cols - 1]
            
            for c_idx_sum in range(current_pivot_col + 1, num_variables):
                coeff_in_equation = A[r_idx][c_idx_sum]
                if abs(coeff_in_equation) < EPSILON: 
                    continue

                var_sum_expr = solution_expressions[c_idx_sum]

                if isinstance(var_sum_expr, dict):
                    if var_sum_expr.get('is_free'): 
                        pivot_var_expr[c_idx_sum] = pivot_var_expr.get(c_idx_sum, 0.0) - coeff_in_equation
                    else:
                        pivot_var_expr['constant_term'] -= coeff_in_equation * var_sum_expr.get('constant_term', 0.0)
                        for free_var_idx_key_internal in free_variable_indices: 
                            coeff_of_free_in_var_sum_expr = var_sum_expr.get(free_var_idx_key_internal, 0.0)
                            if abs(coeff_of_free_in_var_sum_expr) > EPSILON:
                                pivot_var_expr[free_var_idx_key_internal] = \
                                    pivot_var_expr.get(free_var_idx_key_internal, 0.0) - \
                                    coeff_in_equation * coeff_of_free_in_var_sum_expr
                else:
                    print(f"Lỗi logic: Biểu thức cho biến x{c_idx_sum+1} không phải là dict trong trường hợp vô số nghiệm.")
                    return None


            pivot_element_val = A[r_idx][current_pivot_col]
            if abs(pivot_element_val) < EPSILON: 
                is_consistent_for_zero_pivot = True
                if abs(pivot_var_expr['constant_term']) > EPSILON:
                    is_consistent_for_zero_pivot = False
                if is_consistent_for_zero_pivot:
                    for f_idx_check in free_variable_indices:
                        if abs(pivot_var_expr.get(f_idx_check, 0.0)) > EPSILON:
                            is_consistent_for_zero_pivot = False
                            break
                if not is_consistent_for_zero_pivot:
                    print(f"Hệ trở thành vô nghiệm do mâu thuẫn tại hàng {r_idx} (pivot gần bằng 0 và vế phải khác 0).")
                    return None
                else:
                    print(f"Cảnh báo: Pivot gần bằng 0 tại [{r_idx}][{current_pivot_col}] và vế phải cũng bằng 0. Biến x{current_pivot_col+1} có thể là tự do.")

            elif abs(pivot_element_val - 1.0) > EPSILON:
                pivot_var_expr['constant_term'] /= pivot_element_val
                for f_idx_divide in free_variable_indices:
                    pivot_var_expr[f_idx_divide] = pivot_var_expr.get(f_idx_divide, 0.0) / pivot_element_val
            
        for var_idx in range(num_variables):
            expr = solution_expressions[var_idx]
            if isinstance(expr, dict):
                if expr.get('is_free'):
                    # Xác định tên cho biến tự do, ví dụ t1, t2,...
                    free_param_name = f"t{free_variable_indices.index(var_idx) + 1}" if var_idx in free_variable_indices else f"x{var_idx+1}_free"
                    print(f'x{var_idx + 1} = {free_param_name} (biến tự do)')
                else:
                    parts = []
                    const_term = expr.get('constant_term', 0.0)
                    if abs(const_term) > EPSILON or not any(abs(expr.get(f_idx, 0.0)) > EPSILON for f_idx in free_variable_indices):
                        parts.append(f"{const_term:.5f}")
                    
                    for free_idx in free_variable_indices:
                        coeff = expr.get(free_idx, 0.0)
                        if abs(coeff) > EPSILON:
                            sign = "-" if coeff < 0 else "+"
                            abs_coeff = abs(coeff)
                            coeff_str = f"{abs_coeff:.5f}" if abs_coeff != 1.0 else ""
                            # Tên tham số tự do
                            param_name = f"t{free_variable_indices.index(free_idx) + 1}" if free_idx in free_variable_indices else f"x{free_idx+1}_free"
                            if parts and sign == "+":
                                parts.append(f" {sign} ")
                            elif sign == "-":
                                parts.append(f" {sign} ")
                            elif not parts and sign == "+":
                                pass
                            parts.append(f"{coeff_str}{param_name}")

                    final_expr_str = "".join(parts).strip()
                    if not final_expr_str and abs(const_term) < EPSILON:
                        final_expr_str = "0.00000"

                    print(f'x{var_idx + 1} = {final_expr_str if final_expr_str else "0.00000"}')
            else: 
                 if isinstance(expr, float):
                    print(f'x{var_idx + 1} = {expr:.5f}')
                 else:
                    print(f'x{var_idx + 1} = {expr}')
        return solution_expressions

In [30]:

def print_matrix(matrix):
    for row in matrix:
        print(" ".join(f"{value:8.3f}" if isinstance(value, float) else f"{value:8}" for value in row))
    print()

In [31]:
def solve(problems):
    problem_id = 0
    for matrix in problems:
        problem_id += 1
        print(f"\n\tPROBLEM {problem_id}")
        
        if not matrix or not all(len(row) == len(matrix[0]) for row in matrix):
            print("Invalid matrix input.")
            continue

        print("Original Matrix:")
        print_matrix(matrix)

        try:
            A_echelon = Gauss_elimination(matrix)

            print("\nRow Echelon Form:")
            print_matrix(A_echelon)

            back_substitution(A_echelon)
        except Exception as e:
            print(f"An error occurred: {e}")

solve(problems)


	PROBLEM 1
Original Matrix:
       1        2       -1       -1
       2        2        1        1
       3        5       -2       -1


Row Echelon Form:
   1.000    2.000   -1.000   -1.000
   0.000    1.000   -1.500   -1.500
   0.000    0.000    1.000   -1.000

Hệ có nghiệm duy nhất.
x1 = 4.00000
x2 = -3.00000
x3 = -1.00000

	PROBLEM 2
Original Matrix:
       1       -2       -1        1
       2       -3        1        6
       3       -5        0        7
       1        0        5        9


Row Echelon Form:
   1.000   -2.000   -1.000    1.000
   0.000    1.000    3.000    4.000
   0.000    0.000    0.000    0.000
   0.000    0.000    0.000    0.000

Hệ có vô số nghiệm.
x1 = 9.00000 - 5.00000t1
x2 = 4.00000 - 3.00000t1
x3 = t1 (biến tự do)

	PROBLEM 3
Original Matrix:
       1        2        0        2        6
       3        5       -1        6       17
       2        4        1        2       12
       2        0       -7       11        7


Row Echelon Form:
   1.000    

# =============================================================================
# **PHẦN MỞ RỘNG**
# =============================================================================

Trong phần này, chúng ta sẽ tìm hiểu và sử dụng các hàm/phương thức có sẵn từ  các thư viện Python phổ biến như NumPy và SymPy để thực hiện phép khử  Gauss và giải hệ 

phương trình tuyến tính. Mục đích là để so sánh kết quả và hiểu rõ hơn về các giải thuật được tối ưu hóa trong thực tế.

### **Sử dụng thư viện `numpy`** <a id="c4"></a>

`numpy` là một thư viện nền tảng cho tính toán khoa học trong Python, cung cấp các đối tượng mảng đa chiều hiệu suất cao và các công cụ để làm việc với chúng.

**a. Tìm dạng bậc thang (Row-Echelon Form):**

   `numpy` không có một hàm trực tiếp để trả về dạng bậc thang **chính xác** như chúng ta đã tự viết (với các pivot có thể không phải là 1 và các hàng không ở dưới cùng). 
   
   Tuy nhiên, chúng ta có thể sử dụng các phép toán trên hàng hoặc các hàm phân rã ma trận để tiến gần đến nó hoặc để giải hệ.

   *   **Cách tiếp cận phổ biến**: Thường thì người ta sẽ giải hệ trực tiếp thay vì chỉ tìm dạng bậc thang.

   *   **Thao tác thủ công (ví dụ)**: Bạn có thể thử viết một hàm nhỏ sử dụng các phép toán trên mảng `numpy` để mô phỏng lại các bước khử Gauss, nhưng điều này không 
   
   tận dụng được sức mạnh giải hệ sẵn có.

**b. Giải hệ phương trình tuyến tính `Ax = b`:**

   `numpy` cung cấp hàm `numpy.linalg.solve(a, b)` để giải hệ phương trình tuyến tính.

   *   **Input**:

        *   `a`: Ma trận hệ số (mảng 2D).

        *   `b`: Vector vế phải (mảng 1D hoặc 2D).

   *   **Output**: Vector nghiệm `x`.

   *   **Lưu ý**: Hàm này thường được sử dụng cho các hệ có nghiệm duy nhất và ma trận hệ số `a` là ma trận vuông và không suy biến. Nếu ma trận không vuông hoặc suy 
   
   biến (dẫn đến vô nghiệm hoặc vô số nghiệm), nó có thể báo lỗi hoặc trả về kết quả không như mong đợi cho mục đích tìm nghiệm tổng quát.

**Ví dụ với `numpy`:**

In [32]:
import numpy as np
import sympy

# Chọn các ví dụ: prob1 (nghiệm duy nhất), prob5 (vô số nghiệm), prob4 (vô nghiệm)

# Helper function để tách ma trận mở rộng thành A và b cho NumPy
def split_augmented_matrix_for_numpy(augmented_matrix):
    matrix_np = np.array(augmented_matrix, dtype=float)
    if matrix_np.shape[1] <= 1: # Trường hợp chỉ có 1 cột hoặc không có cột b
        return None, None
    A = matrix_np[:, :-1]
    b = matrix_np[:, -1]
    return A, b

# --- VÍ DỤ VỚI prob1 (nghiệm duy nhất) ---
print("\n--- NumPy với Problem 1 (prob1) ---")
A_np_p1, b_np_p1 = split_augmented_matrix_for_numpy(prob1)
if A_np_p1 is not None:
    print("Ma trận A:\n", A_np_p1)
    print("Vector b:\n", b_np_p1)
    try:
        x_np_p1 = np.linalg.solve(A_np_p1, b_np_p1)
        print(f"Nghiệm theo NumPy (linalg.solve): {x_np_p1}")

        # So sánh với code của bạn
        print("\nSo sánh với code tự viết cho Problem 1:")
        A_echelon_custom_p1 = Gauss_elimination(prob1) 

        x_custom_p1 = back_substitution(A_echelon_custom_p1) 
        if x_custom_p1 is not None and isinstance(x_custom_p1[0], float): # Kiểm tra là nghiệm duy nhất
             try:
                print(f"Nghiệm theo code tự viết: {x_custom_p1}")
                print(f"So sánh (allclose): {np.allclose(x_np_p1, np.array(x_custom_p1))}")
             except TypeError:
                print("Không thể so sánh trực tiếp, kiểu dữ liệu nghiệm từ code tự viết không phải list số.")
        else:
            print("Code tự viết không trả về nghiệm duy nhất dạng list số cho Problem 1 để so sánh.")


    except np.linalg.LinAlgError as e:
        print(f"Lỗi NumPy (linalg.solve): {e} - Có thể ma trận suy biến hoặc không vuông.")
    except Exception as e_custom:
        print(f"Lỗi khi chạy code tự viết cho Problem 1: {e_custom}")
else:
    print("Không thể tách ma trận cho Problem 1.")


# --- VÍ DỤ VỚI prob5 (vô số nghiệm) ---
print("\n--- NumPy với Problem 5 (prob5) ---")
A_np_p5, b_np_p5 = split_augmented_matrix_for_numpy(prob5)
if A_np_p5 is not None:
    print("Ma trận A:\n", A_np_p5)
    print("Vector b:\n", b_np_p5)
    try:
        x_np_lstsq_p5, residuals_p5, rank_A_p5, s_vals_p5 = np.linalg.lstsq(A_np_p5, b_np_p5, rcond=None)
        print(f"Rank của A (theo NumPy lstsq): {rank_A_p5}")
        print(f"Số biến: {A_np_p5.shape[1]}")

        if rank_A_p5 < A_np_p5.shape[1]:
            print("Hệ có vẻ có vô số nghiệm (hoặc vô nghiệm nếu không nhất quán).")
            print(f"Một nghiệm cụ thể (ít bình phương) từ NumPy: {x_np_lstsq_p5}")
            # Kiểm tra tính nhất quán
            if np.allclose(A_np_p5 @ x_np_lstsq_p5, b_np_p5):
                 print("Hệ có vẻ nhất quán (có nghiệm).")
            else:
                 # Kiểm tra residuals, nếu residuals lớn thì có thể là vô nghiệm
                 if residuals_p5.size > 0 and np.sum(residuals_p5**2) > 1e-9 :
                     print("Hệ có vẻ không nhất quán (vô nghiệm) dựa trên residuals.")
                 elif not (residuals_p5.size > 0): # residuals rỗng có nghĩa là khớp hoàn hảo
                     print("Hệ có vẻ nhất quán (có nghiệm).")
                 else: # residuals nhỏ
                     print("Hệ có vẻ nhất quán (có nghiệm), nhưng có thể có sai số nhỏ.")


        # So sánh với code của bạn
        print("\nSo sánh với code tự viết cho Problem 5:")
        A_echelon_custom_p5 = Gauss_elimination(prob5)
        solution_custom_p5 = back_substitution(A_echelon_custom_p5)

    except np.linalg.LinAlgError as e:
        print(f"Lỗi NumPy (Problem 5): {e}")
    except Exception as e_custom:
        print(f"Lỗi khi chạy code tự viết cho Problem 5: {e_custom}")
else:
    print("Không thể tách ma trận cho Problem 5.")


# --- VÍ DỤ VỚI prob4 (vô nghiệm) ---
print("\n--- NumPy với Problem 4 (prob4) ---")
A_np_p4, b_np_p4 = split_augmented_matrix_for_numpy(prob4)
if A_np_p4 is not None:
    print("Ma trận A:\n", A_np_p4)
    print("Vector b:\n", b_np_p4)
    try:
        x_np_lstsq_p4, residuals_p4, rank_A_p4, _ = np.linalg.lstsq(A_np_p4, b_np_p4, rcond=None)
        print(f"Rank của A (theo NumPy lstsq): {rank_A_p4}")
        print(f"Một nghiệm 'gần đúng' (ít bình phương) từ NumPy: {x_np_lstsq_p4}")
        
        # Kiểm tra tính nhất quán
        if not np.allclose(A_np_p4 @ x_np_lstsq_p4, b_np_p4):
            print("Hệ có vẻ không nhất quán (vô nghiệm) dựa trên kiểm tra A@x vs b.")
            if residuals_p4.size > 0 and np.sum(residuals_p4**2) > 1e-9 :
                 print("Xác nhận bằng residuals: Hệ không nhất quán (vô nghiệm).")
        else:
            print("Hệ có vẻ nhất quán. Kiểm tra rank để xem nghiệm duy nhất hay vô số.")
            if rank_A_p4 == A_np_p4.shape[1]:
                print("Có thể là nghiệm duy nhất.")
            else:
                print("Có thể là vô số nghiệm.")

        # So sánh với code của bạn
        print("\nSo sánh với code tự viết cho Problem 4:")
        A_echelon_custom_p4 = Gauss_elimination(prob4)
        solution_custom_p4 = back_substitution(A_echelon_custom_p4)
        # Nếu solution_custom_p4 là None, code của bạn đã phát hiện vô nghiệm.

    except np.linalg.LinAlgError as e:
        print(f"Lỗi NumPy (Problem 4): {e}")
    except Exception as e_custom:
        print(f"Lỗi khi chạy code tự viết cho Problem 4: {e_custom}")
else:
    print("Không thể tách ma trận cho Problem 4.")


--- NumPy với Problem 1 (prob1) ---
Ma trận A:
 [[ 1.  2. -1.]
 [ 2.  2.  1.]
 [ 3.  5. -2.]]
Vector b:
 [-1.  1. -1.]
Nghiệm theo NumPy (linalg.solve): [ 4. -3. -1.]

So sánh với code tự viết cho Problem 1:
Hệ có nghiệm duy nhất.
x1 = 4.00000
x2 = -3.00000
x3 = -1.00000
Nghiệm theo code tự viết: [4.0, -3.0, -1.0]
So sánh (allclose): True

--- NumPy với Problem 5 (prob5) ---
Ma trận A:
 [[ 1.  2. -2.]
 [ 3. -1.  1.]
 [-1.  5. -5.]]
Vector b:
 [3. 1. 5.]
Rank của A (theo NumPy lstsq): 2
Số biến: 3
Hệ có vẻ có vô số nghiệm (hoặc vô nghiệm nếu không nhất quán).
Một nghiệm cụ thể (ít bình phương) từ NumPy: [ 0.71428571  0.57142857 -0.57142857]
Hệ có vẻ nhất quán (có nghiệm).

So sánh với code tự viết cho Problem 5:
Hệ có vô số nghiệm.
x1 = 0.71429
x2 = 1.14286 + t1
x3 = t1 (biến tự do)

--- NumPy với Problem 4 (prob4) ---
Ma trận A:
 [[ 2. -4. -1.]
 [ 1. -3.  1.]
 [ 3. -5. -3.]]
Vector b:
 [1. 1. 2.]
Rank của A (theo NumPy lstsq): 2
Một nghiệm 'gần đúng' (ít bình phương) từ NumPy: [ 0.126


### **Sử dụng Thư viện `sympy`** <a id="c5"></a>

`sympy` là một thư viện Python cho toán học ký hiệu. Nó rất mạnh trong việc tìm dạng bậc thang rút gọn (RREF) và giải hệ phương trình một cách chính xác,  bao gồm cả việc biểu diễn 

nghiệm tổng quát cho trường hợp vô số nghiệm.

**a. Tìm dạng bậc thang rút gọn (RREF - Row-Reduced Echelon Form):**

   `sympy` cung cấp phương thức `rref()` cho đối tượng `Matrix`.

   *   **Input**: Ma trận Sympy.

   *   **Output**: Một tuple gồm hai phần tử:

        1.  Ma trận ở dạng RREF.

        2.  Một tuple chứa các chỉ số cột của các cột pivot.

**b. Giải hệ phương trình tuyến tính:**

   `sympy` cung cấp hàm `sympy.solve_linear_system(system, *symbols)` và `sympy.linsolve(system, *symbols)`.

   *   `solve_linear_system(system, *symbols)`:

         *   `system`: Ma trận mở rộng `[A|b]`.

        *   `*symbols`: Các biến của hệ (ví dụ: `x, y, z`).

        *   Output: Một dictionary biểu diễn nghiệm.

   *   `linsolve(system, *symbols)`:

        *   Tương tự như trên nhưng thường trả về một `FiniteSet` chứa một tuple nghiệm (cho nghiệm duy nhất) hoặc một biểu thức nghiệm tổng quát sử dụng các 
        
        biến tự do được tạo tự động (ví dụ `tau0, tau1`).

**Ví dụ với `sympy`:**

In [33]:
import sympy

from sympy import init_printing

init_printing(use_unicode=True)

# --- VÍ DỤ VỚI prob1 (Nghiệm duy nhất) ---
print("\n--- SymPy với Problem 1 (prob1) ---")
# Ma trận mở rộng cho SymPy
A_sym_p1_matrix = sympy.Matrix(prob1)
print("Ma trận mở rộng:")
sympy.pprint(A_sym_p1_matrix)

# Tìm RREF
rref_p1, pivots_p1 = A_sym_p1_matrix.rref()
print("\nDạng RREF theo SymPy:")
sympy.pprint(rref_p1)
print(f"Các cột pivot: {pivots_p1}")

# Giải hệ
num_vars_p1 = A_sym_p1_matrix.shape[1] - 1
vars_p1 = sympy.symbols(f'x:{num_vars_p1}') 

try:
    solution_sym_p1 = sympy.linsolve(A_sym_p1_matrix, vars_p1)
    print("\nNghiệm theo SymPy (linsolve):")
    sympy.pprint(solution_sym_p1)
    # So sánh với code tự viết (bằng cách diễn giải kết quả)
except Exception as e:
    print(f"Lỗi SymPy: {e}")


# --- VÍ DỤ VỚI prob5 (Vô số nghiệm) ---
print("\n--- SymPy với Problem 5 (prob5) ---")
A_sym_p5_matrix = sympy.Matrix(prob5)
print("Ma trận mở rộng:")
sympy.pprint(A_sym_p5_matrix)

rref_p5, pivots_p5 = A_sym_p5_matrix.rref()
print("\nDạng RREF theo SymPy:")
sympy.pprint(rref_p5)
print(f"Các cột pivot: {pivots_p5}")

num_vars_p5 = A_sym_p5_matrix.shape[1] - 1
vars_p5 = sympy.symbols(f'x:{num_vars_p5}')
try:
    solution_sym_p5 = sympy.linsolve(A_sym_p5_matrix, vars_p5)
    print("\nNghiệm (vô số) theo SymPy (linsolve):")
    sympy.pprint(solution_sym_p5)
except Exception as e:
    print(f"Lỗi SymPy: {e}")


# --- VÍ DỤ VỚI prob4 (vô nghiệm) ---
print("\n--- SymPy với Problem 4 (prob4) ---")
A_sym_p4_matrix = sympy.Matrix(prob4)
print("Ma trận mở rộng:")
sympy.pprint(A_sym_p4_matrix)

rref_p4, pivots_p4 = A_sym_p4_matrix.rref()
print("\nDạng RREF theo SymPy:")
sympy.pprint(rref_p4) # Nếu vô nghiệm, sẽ thấy hàng [0,0,...,0,1]
print(f"Các cột pivot: {pivots_p4}")

num_vars_p4 = A_sym_p4_matrix.shape[1] - 1
vars_p4 = sympy.symbols(f'x:{num_vars_p4}')
try:
    solution_sym_p4 = sympy.linsolve(A_sym_p4_matrix, vars_p4)
    print("\nNghiệm theo SymPy (linsolve):")
    sympy.pprint(solution_sym_p4) # Sẽ là sympy.EmptySet nếu vô nghiệm
    if solution_sym_p4 == sympy.EmptySet:
        print("SymPy xác nhận hệ vô nghiệm.")
except Exception as e:
    print(f"Lỗi SymPy: {e}")


--- SymPy với Problem 1 (prob1) ---
Ma trận mở rộng:
⎡1  2  -1  -1⎤
⎢            ⎥
⎢2  2  1   1 ⎥
⎢            ⎥
⎣3  5  -2  -1⎦

Dạng RREF theo SymPy:
⎡1  0  0  4 ⎤
⎢           ⎥
⎢0  1  0  -3⎥
⎢           ⎥
⎣0  0  1  -1⎦
Các cột pivot: (0, 1, 2)

Nghiệm theo SymPy (linsolve):
{(4, -3, -1)}

--- SymPy với Problem 5 (prob5) ---
Ma trận mở rộng:
⎡1   2   -2  3⎤
⎢             ⎥
⎢3   -1  1   1⎥
⎢             ⎥
⎣-1  5   -5  5⎦

Dạng RREF theo SymPy:
⎡1  0  0   5/7⎤
⎢             ⎥
⎢0  1  -1  8/7⎥
⎢             ⎥
⎣0  0  0    0 ⎦
Các cột pivot: (0, 1)

Nghiệm (vô số) theo SymPy (linsolve):
{(5/7, x₂ + 8/7, x₂)}

--- SymPy với Problem 4 (prob4) ---
Ma trận mở rộng:
⎡2  -4  -1  1⎤
⎢            ⎥
⎢1  -3  1   1⎥
⎢            ⎥
⎣3  -5  -3  2⎦

Dạng RREF theo SymPy:
⎡1  0  -7/2  0⎤
⎢             ⎥
⎢0  1  -3/2  0⎥
⎢             ⎥
⎣0  0   0    1⎦
Các cột pivot: (0, 1, 3)

Nghiệm theo SymPy (linsolve):
∅
SymPy xác nhận hệ vô nghiệm.


### **So sánh và nhận xét kết quả** <a id="c6"></a>

Sau khi thực hiện giải các hệ phương trình bằng code tự viết và các thư viện NumPy, SymPy, chúng ta có các kết quả và nhận xét sau:

1.  **Độ Chính Xác và Ổn Định Số Học**:

    *   **Code tự viết**: Độ chính xác phụ thuộc vào việc xử lý số thực (ví dụ, sử dụng `EPSILON`). Có thể nhạy cảm với sai số làm tròn, do em không viết theo chiến lược 
    
    "pivoting" (chọn pivot lớn nhất). Hàm `Gauss_elimination` của em có chuẩn hóa pivot.

    *   **NumPy**: Được tối ưu hóa cao và sử dụng các thuật toán số ổn định (thường dựa trên các thư viện LAPACK đã được kiểm chứng)

    *   **SymPy**: Thực hiện tính toán ký hiệu chính xác, nên không bị ảnh hưởng bởi sai số làm tròn số thực theo cách NumPy. Khi cần kết quả số, nó có thể tính toán với 
    
    độ chính xác tùy ý.

2.  **Khả Năng Xử Lý các Trường Hợp**:

    *   **Nghiệm duy nhất**: Cả ba đều xử lý tốt.

    *   **Vô nghiệm**: Code tự viết và SymPy phát hiện rõ ràng. NumPy cần diễn giải từ lỗi của `solve` hoặc `residuals` của `lstsq`.

    *   **Vô số nghiệm**: Code tự viết và SymPy cung cấp nghiệm tổng quát. SymPy biểu diễn nó một cách toán học tự nhiên hơn với các tham số tự do. NumPy `lstsq` chỉ cho 
    
    một nghiệm cụ thể.

3.  **Dạng Bậc Thang và RREF**:

    *   `Gauss_elimination` của em tạo ra dạng bậc thang (pivot được chuẩn hóa là 1).

    *   `sympy.Matrix.rref()` tạo ra dạng bậc thang rút gọn (RREF), đây là dạng chuẩn tắc và duy nhất, giúp việc đọc nghiệm dễ dàng hơn.

4.  **Sự Tiện Lợi và Tốc Độ**:

    *   **Thư viện (NumPy, SymPy)**: Cực kỳ tiện lợi, chỉ cần một vài dòng code. NumPy rất nhanh cho các phép toán số trên ma trận lớn. SymPy mạnh về tính chính xác và 
    
    biểu diễn ký hiệu, nhưng có thể chậm hơn NumPy cho các bài toán số thuần túy.

    *   **Code tự viết**: Đòi hỏi nhiều nỗ lực hơn để viết và gỡ lỗi, nhưng mang lại sự hiểu biết sâu sắc về thuật toán. Tốc độ thực thi có thể chậm hơn đáng kể so với các 
    
    hàm đã biên dịch của NumPy cho ma trận lớn.

5.  **Kết luận nên dùng khi nào**:

    *   **Học và hiểu thuật toán**: Tự viết code là cách tốt nhất.

    *   **Ứng dụng thực tế cần tốc độ và độ tin cậy số**: NumPy là lựa chọn tốt nhất.

    *   **Cần kết quả chính xác tuyệt đối, biểu diễn nghiệm tổng quát phức tạp, hoặc các thao tác toán học ký hiệu**: SymPy là lựa chọn tốt nhất.

# =============================================================================
# **PHẦN MÔ TẢ Ý TƯỞNG THỰC HIỆN VÀ MÔ TẢ CÁC HÀM** <a id="c7"></a>
# =============================================================================

### **Hàm `deepcopy_matrix(matrix)`**
Hàm này tạo ra một ma trận mới hoàn toàn độc lập với ma trận gốc, đảm bảo các thao tác trên bản sao không ảnh hưởng đến ma trận đầu vào.

### **Hàm `Gauss_elimination(A_orig)`**

*   **Input**: `A_orig` (ma trận mở rộng `[A|b]`).

*   **Output**: Ma trận `A` (bản sao đã biến đổi) ở dạng bậc thang, với các pivot được chuẩn hóa thành 1.

*   **Mô tả**:

    1.  Tạo bản sao sâu `A` của `A_orig`.

    2.  Khởi tạo con trỏ hàng `i = 0` và con trỏ cột bắt đầu tìm kiếm `j = 0`.

    3.  Lặp khi `i < số hàng` và `j < số cột - 1`:

        a.  **Tìm Cột Pivot**:

        * Tìm `pivot_col`: cột đầu tiên (từ `j` trở đi) có phần tử khác không tính từ hàng `i` trở xuống.

        *   Nếu không tìm thấy `pivot_col`, thoát vòng lặp.

        b.  **Chọn Hàng Pivot & Hoán Vị**:

        * Tìm `pivot_row`: hàng đầu tiên (từ `i` trở xuống) sao cho `A[pivot_row][pivot_col] != 0`.

        * Hoán vị hàng `i` với hàng `pivot_row` (nếu `i != pivot_row`).
            
        c.  **Chuẩn Hóa & Khử**:
        
        * Lấy `pivot_element = A[i][pivot_col]`.

        * Nếu `pivot_element != 0`:

            1.  **Chuẩn hóa hàng `i`**: Chia các phần tử của hàng `i` (từ `pivot_col` trở đi) cho `pivot_element` (để `A[i][pivot_col] = 1`).

            2.  **Khử dưới pivot**: Với mỗi hàng `k` dưới hàng `i`, trừ đi `A[k][pivot_col]` nhân với hàng `i` (đã chuẩn hóa) khỏi hàng `k`, bắt đầu từ `pivot_col`.
                
        * *(Nếu `pivot_element == 0`, in cảnh báo).*

        d.  **Cập nhật con trỏ**: `i++`, `j = pivot_col + 1`.

    4.  Trả về ma trận `A`.

### **Hàm `back_substitution(A_echelon)`**

*   **Input**: `A_echelon_` (ma trận mở rộng `[A|b]` đã ở dạng bậc thang).

*   **Output**:

    *   `None` (và in thông báo) nếu hệ vô nghiệm.

    *   `list` các `float` (nghiệm `[x0, ..., xn-1]`) (và in thông báo) nếu hệ có nghiệm duy nhất.

    *   `list` các `dict` (biểu diễn nghiệm tổng quát) (và in thông báo) nếu hệ có vô số nghiệm.

*   **Mô tả**:

    1.  **Khởi tạo**: Xác định kích thước ma trận, số biến, hằng số `EPSILON`.

    2.  **Tìm Pivot & Vô nghiệm sớm**:

        *   Xác định `pivot_col_for_row[r_idx]`: cột chứa pivot cho hàng `r_idx`.

        *   Nếu gặp hàng `[0...0 | k]` với `k != 0`, trả về `None` (vô nghiệm).

    3.  **Phân loại Biến**: Xác định `pivot_variable_indices` (biến cơ sở) và `free_variable_indices` (biến tự do).

    4.  **Giải Hệ**:

        *   **Nghiệm Duy Nhất (`not free_variable_indices`)**:

            a.  Duyệt ngược các hàng.

            b.  Với mỗi hàng pivot, tính giá trị biến cơ sở `x_pivot` bằng cách:

            *   `x_pivot = (RHS - sum(coeff * đã_giải_x_khác)) / pivot_element`.

            c.  Lưu kết quả số vào `solution_expressions`.

        *   **Vô Số Nghiệm (`free_variable_indices`)**:

            a.  Khởi tạo `solution_expressions`: biến tự do là `{'is_free': True, ...}`, biến cơ sở là `{'is_free': False, 'constant_term': 0, ...}`.

            b.  Duyệt ngược các hàng.

            c.  Với mỗi hàng pivot, xây dựng biểu thức cho biến cơ sở `x_pivot` theo hằng số và các biến tự do, dựa trên các biến đã giải ở vế phải.

            d.  Nếu `pivot_element` của hàng hiện tại không phải là 1 (và không phải 0), chia toàn bộ biểu thức của `x_pivot` cho `pivot_element`.

    5.  In thông báo và các nghiệm/biểu thức nghiệm. Trả về `solution_expressions`.

### **Hàm `print_matrix(matrix)`**
Hàm này in ma trận `matrix` ra màn hình với định dạng dễ đọc. Các phần tử số nguyên được in nguyên dạng, các phần tử số thực được in với 3 chữ số thập phân, tất cả được căn lề sao cho 

các cột thẳng hàng, giúp người đọc dễ quan sát và phân tích ma trận hơn.

### **Hàm `solve(problems)`**

Hàm này thực hiện quá trình giải hệ phương trình tuyến tính bằng phương pháp khử Gauss, bao gồm:

* In ma trận đầu vào (ma trận mở rộng của hệ).

* Áp dụng thuật toán Gauss_elimination để đưa ma trận về dạng bậc thang (row echelon form) và in kết quả.

* Giải hệ phương trình bằng phép thế ngược (back_substitution) và in nghiệm tìm được.

* Nếu ma trận đầu vào không hợp lệ hoặc xảy ra lỗi trong quá trình tính toán, hàm sẽ in thông báo lỗi tương ứng.
